spring:
  application:
    name: User-management
server:
  port: 8081 # or any desired port

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
